set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR amd64)

set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)

set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(XMRIG_DEPS ../xmrig-deps/gcc/x64)
set(HWLOC_INCLUDE_DIR ${XMRIG_DEPS}/include/hwloc)
set(HWLOC_LIBRARY ${XMRIG_DEPS}/lib/libhwloc.a)
set(UV_INCLUDE_DIR ${XMRIG_DEPS}/include/uv)
set(UV_LIBRARY ${XMRIG_DEPS}/lib/libuv.a)
set(OPENSSL_INCLUDE_DIR ${XMRIG_DEPS}/include/openssl)
set(OPENSSL_CRYPTO_LIBRARY ${XMRIG_DEPS}/lib/libcrypto.a)
set(OPENSSL_ROOT_DIR ${XMRIG_DEPS})

set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".a" CONFIG)
set(BUILD_SHARED_LIBS OFF)
